Return-path: <jpython-interest-admin@python.org>
Received: from mta540.mail.yahoo.com [216.136.131.22] by receive.turbosport.com [63.118.43.131]
	with SMTP (MDaemon.v3.5.2.R)
	for <bbbsss@turbosport.com>; Sun, 18 Feb 2001 02:25:20 -0600
Message-ID: <20010218082300.42071.qmail@mta540.mail.yahoo.com>
Received: from mta540.mail.yahoo.com for bbbsss@turbosport.com; Feb 18 00:23:00 2001 -0800
Received: from smtp015.mail.yahoo.com (216.136.173.59)
X-Yahoo-Forwarded: from aaaaa_20@yahoo.com to bbbsss@turbosport.com
  by mta540.mail.yahoo.com with SMTP; 18 Feb 2001 00:23:00 -0800 (PST)
Date: 18 Feb 2001 08:22:57 -0000
From: MAILER-DAEMON@yahoo.com
To: aaaaa@yahoo.com
Subject: failure delivery
X-MDRcpt-To: bbbsss@turbosport.com
X-MDRemoteIP: 216.136.131.22
X-Return-Path: jpython-interest-admin@python.org
X-MDaemon-Deliver-To: bbbsss@turbosport.com

Message from  yahoo.com.
Unable to deliver message to the following address(es).

<userx@example.com>:
Sorry, I wasn't able to establish an SMTP connection. (#4.4.1)
I'm not going to try again; this message has been in the queue too long.

--- Original message follows.

Message removed

